# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Temperature', models.CharField(max_length=20)),
                ('Temrange', models.CharField(max_length=20)),
                ('Updatetime', models.DateTimeField(auto_now=True, max_length=20)),
                ('Alarm', models.BooleanField(max_length=10)),
                ('Operation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=20)),
                ('Temperature', models.CharField(max_length=20)),
                ('Updatetime', models.DateTimeField(auto_now=True, max_length=20)),
                ('Temrange', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Person'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Person'),
        ),
    ]
