# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Alarm',
            field=models.CharField(default='OFF', max_length=20),
            preserve_default=False,
        ),
    ]
